import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  index("routes/public/home.tsx"),
  route("login", "routes/public/login.tsx"),
  route("forgot-password", "routes/public/forgot-password.tsx"),
  route("reset-password", "routes/public/reset-password.tsx"),
  route("change-password", "routes/public/change-password.tsx"),
  route("privacy-policy", "routes/public/privacy-policy.tsx"),
  route("terms-of-use", "routes/public/terms-of-use.tsx"),
  route("help", "routes/public/help.tsx"),
  route("faqs", "routes/public/faqs.tsx"),
  route("contact-us", "routes/public/contact-us.tsx"),
  route("unauthorized", "routes/unauthorized.tsx"),

  // Authenticated area â€” AppShell provides theme, auth guard, and chrome.
  layout("layouts/app-shell.tsx", [
    route("dashboard", "routes/app/dashboard.tsx"),
    route("administrators", "routes/app/administrators.tsx"),
    route("permissions", "routes/app/permissions.tsx"),
    route("buildings", "routes/app/buildings.tsx"),
    route("rooms", "routes/app/rooms.tsx"),
    route("departments", "routes/app/departments.tsx"),
    route("programs", "routes/app/programs.tsx"),
    route("subjects", "routes/app/subjects.tsx"),
    route("subjects/new", "routes/app/subjects-new.tsx"),
    route("sets", "routes/app/sets.tsx"),
    route("deans", "routes/app/deans.tsx"),
    route("dean/subjects", "routes/app/dean-subjects.tsx"),
    route("dean/instructors", "routes/app/dean-instructors.tsx"),
    route("dean/subject-assignments", "routes/app/dean-subject-assignments.tsx"),
    route("faculty", "routes/app/faculty.tsx"),
    route("faculty-loads", "routes/app/faculty-loads.tsx"),
    route("schedules", "routes/app/schedules/index.tsx"),
    route("schedules/weekly-hour-allocations", "routes/app/schedules/weekly-hour-allocations.tsx"),
    route("schedules/regular-class", "routes/app/schedules/regular-class.tsx"),
    route("schedules/irregular-class", "routes/app/schedules/irregular-class.tsx"),
    route("schedules/new", "routes/app/schedules-new.tsx"),
    route("academic-year", "routes/app/academic-year.tsx"),
    route("faculty-schedule", "routes/app/faculty-schedule.tsx"),
    route("student-schedule", "routes/app/student-schedule.tsx"),
    route("curriculum", "routes/app/curriculum.tsx"),
    route("students", "routes/app/students.tsx"),
    route("students-regular", "routes/app/students-regular.tsx"),
    route("students-irregular", "routes/app/students-irregular.tsx"),
    route("classroom-mapping", "routes/app/classroom-mapping.tsx"),
    route("audit", "routes/app/audit.tsx"),

    layout("layouts/settings-layout.tsx", [
      route("settings", "routes/app/settings/index.tsx"),
      route("settings/profile", "routes/app/settings/profile.tsx"),
      route("settings/notifications", "routes/app/settings/notifications.tsx"),
      route("settings/security", "routes/app/settings/security.tsx"),
      route("settings/recently-deleted", "routes/app/settings/recently-deleted.tsx"),
    ]),
  ]),
] satisfies RouteConfig;
