import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  index("routes/public/home.tsx"),
  route("login", "routes/public/login.tsx"),
  route("forgot-password", "routes/public/forgot-password.tsx"),
  route("reset-password", "routes/public/reset-password.tsx"),
  route("change-password", "routes/public/change-password.tsx"),
  route("privacy-policy", "routes/public/privacy-policy.tsx"),
  route("terms-of-use", "routes/public/terms-of-use.tsx"),
  route("help", "routes/public/help.tsx"),
  route("faqs", "routes/public/faqs.tsx"),
  route("contact-us", "routes/public/contact-us.tsx"),
  route("unauthorized", "routes/unauthorized.tsx"),

  // Authenticated area — AppShell provides theme, auth guard, and chrome.
  layout("layouts/app-shell.tsx", [
    route("dashboard", "routes/app/dashboard.tsx"),
    route("administrators", "routes/app/administrators.tsx"),
    route("administrators/new", "routes/app/administrators-new.tsx"),
    route("permissions", "routes/app/permissions.tsx"),
    route("facilities", "routes/app/facilities.tsx"),
    route("facilities/new", "routes/app/facilities/new.tsx"),
    route("facilities/:buildingId", "routes/app/facilities/$buildingId.tsx"),
    route("buildings", "routes/app/buildings.tsx"),
    route("buildings/new", "routes/app/buildings/new.tsx"),
    route("rooms", "routes/app/rooms.tsx"),
    route("departments", "routes/app/departments.tsx"),
    route("departments/:departmentId", "routes/app/departments/$departmentId.tsx"),
    route("program-curricula", "routes/app/program-curricula.tsx"),
    route("program-curricula/new", "routes/app/program-curricula-new.tsx"),
    route("sets", "routes/app/sets.tsx"),
    route("dean/subjects", "routes/app/dean-subjects.tsx"),
    route("dean/instructors", "routes/app/dean-instructors.tsx"),
    route("subject-offering", "routes/app/subject-offering.tsx"),
    route("subject-offering/audit-logs", "routes/app/assignment-audit-logs.tsx"),
    route("major-schedules", "routes/app/major-schedules.tsx"),
    route("schedule-responses", "routes/app/schedule-responses.tsx"),
    route("shift-requests", "routes/app/shift-requests.tsx"),
    route("shift-requests/:releaseId", "routes/app/shift-request-detail.tsx"),
    route("teaching-terms/:id", "routes/app/teaching-term.tsx"),
    route("dean/schedule-approvals", "routes/app/dean-schedule-approvals.tsx"),
    route("dean/schedule-approvals/:id", "routes/app/dean-schedule-approval-detail.tsx"),
    route("faculty", "routes/app/faculty.tsx"),
    route("faculty/new", "routes/app/faculty-new.tsx"),
    route("faculty-loads", "routes/app/faculty-loads.tsx"),
    route("schedules", "routes/app/schedules/index.tsx"),
    route("schedules/term-calendar", "routes/app/schedules/term-calendar.tsx"),
    route("schedules/weekly-hour-allocations", "routes/app/schedules/weekly-hour-allocations.tsx"),
    route("schedules/subject-hour-overrides", "routes/app/schedules/subject-hour-overrides.tsx"),
    route("schedules/class-mode-policies", "routes/app/schedules/class-mode-policies.tsx"),
    route("schedules/lab-analysis", "routes/app/schedules/lab-analysis.tsx"),
    route("schedules/regular-class", "routes/app/schedules/regular-class.tsx"),
    route("schedules/irregular-class", "routes/app/schedules/irregular-class.tsx"),
    route("schedules/new", "routes/app/schedules-new.tsx"),
    route("academic-term", "routes/app/academic-term.tsx"),
    route("academic-terms", "routes/app/academic-terms/index.tsx"),
    route("academic-terms/school-years", "routes/app/academic-terms/school-years.tsx"),
    route("academic-terms/semesters", "routes/app/academic-terms/semesters.tsx"),
    route("academic-terms/term-closure", "routes/app/academic-terms/term-closure.tsx"),
    route("academic-terms/audit-log", "routes/app/academic-terms/audit-log.tsx"),
    route("faculty-loading", "routes/app/faculty-loading.tsx"),
    route("faculty-schedule", "routes/app/faculty-schedule.tsx"),
    route("student-schedule", "routes/app/student-schedule.tsx"),
    route("students", "routes/app/students.tsx"),
    route("students-regular", "routes/app/students-regular.tsx"),
    route("students-irregular", "routes/app/students-irregular.tsx"),

    // Enrollment — separate from the routes above, which stay as they are.
    route("enrollment/students", "routes/app/enrollment/students.tsx"),
    route("enrollment/regular-students", "routes/app/enrollment/redirect-regular-students.tsx"),
    route("enrollment/irregular-students", "routes/app/enrollment/redirect-irregular-students.tsx"),
    route("enrollment/new", "routes/app/enrollment/new.tsx"),
    route("enrollment/re-enroll", "routes/app/enrollment/re-enroll.tsx"),
    route("enrollment/re-enroll/already-enrolled", "routes/app/enrollment/re-enroll-already-enrolled.tsx"),
    route("classroom-mapping", "routes/app/classroom-mapping.tsx"),
    route("audit", "routes/app/audit.tsx"),

    layout("layouts/settings-layout.tsx", [
      route("settings", "routes/app/settings/index.tsx"),
      route("settings/account-details", "routes/app/settings/account-details.tsx"),
      route("settings/security", "routes/app/settings/security.tsx"),
      route("settings/archive", "routes/app/settings/archive.tsx"),
      route("settings/dev-tools", "routes/app/settings/dev-tools.tsx"),
    ]),
  ]),
] satisfies RouteConfig;
