/**
 * AUTO-GENERATED TYPESCRIPT MODEL DEFINITIONS
 * Generated from backend SQLAlchemy models in class-scheduling-backend.
 * Do not edit this file directly. Regenerate via DB_To_TypeScript_Generator.bat
 */

/** Backend Model: AccountStatusAuditLog (Table: `account_status_audit_logs`) */
export interface BackendAccountStatusAuditLog {
  action: string;
  id: number;
  reason: string | null;
}

/** Frontend camelCase Mapped Model: AccountStatusAuditLog */
export interface AccountStatusAuditLogModel {
  action: string;
  id: number;
  reason: string | null;
}

/** Backend Model: Address (Table: `addresses`) */
export interface BackendAddress {
  barangay: string;
  city_municipality: string;
  id: number;
  province: string | null;
  region: string;
  street: string;
  zip_code: string;
}

/** Frontend camelCase Mapped Model: Address */
export interface AddressModel {
  barangay: string;
  cityMunicipality: string;
  id: number;
  province: string | null;
  region: string;
  street: string;
  zipCode: string;
}

/** Backend Model: Building (Table: `buildings`) */
export interface BackendBuilding {
  building_name: string;
  deactivated_at: string | null;
  floor_count: number;
  id: number;
  is_active: boolean;
}

/** Frontend camelCase Mapped Model: Building */
export interface BuildingModel {
  buildingName: string;
  deactivatedAt: string | null;
  floorCount: number;
  id: number;
  isActive: boolean;
}

/** Backend Model: CurriculumDetail (Table: `curriculum_details`) */
export interface BackendCurriculumDetail {
  id: number;
  program_id: number;
  semester_number: number;
  subject_id: number;
  year_level: number;
}

/** Frontend camelCase Mapped Model: CurriculumDetail */
export interface CurriculumDetailModel {
  id: number;
  programId: number;
  semesterNumber: number;
  subjectId: number;
  yearLevel: number;
}

/** Backend Model: Day (Table: `days`) */
export interface BackendDay {
  day_of_week: string;
  duration: number | null;
  end_time: string;
  id: number;
  schedule_date: string | null;
  start_time: string;
}

/** Frontend camelCase Mapped Model: Day */
export interface DayModel {
  dayOfWeek: string;
  duration: number | null;
  endTime: string;
  id: number;
  scheduleDate: string | null;
  startTime: string;
}

/** Backend Model: DeanContactInfo (Table: `dean_contact_info`) */
export interface BackendDeanContactInfo {
  dean_profile_id: number;
  email: string;
  id: number;
  mobile: string;
}

/** Frontend camelCase Mapped Model: DeanContactInfo */
export interface DeanContactInfoModel {
  deanProfileId: number;
  email: string;
  id: number;
  mobile: string;
}

/** Backend Model: DeanMajorSchedule (Table: `dean_major_schedules`) */
export interface BackendDeanMajorSchedule {
  id: number;
  mode: string;
  semester_number: number;
}

/** Frontend camelCase Mapped Model: DeanMajorSchedule */
export interface DeanMajorScheduleModel {
  id: number;
  mode: string;
  semesterNumber: number;
}

/** Backend Model: DeanProfile (Table: `dean_profiles`) */
export interface BackendDeanProfile {
  civil_status: string;
  department_id: number;
  first_name: string;
  gender: string;
  id: number;
  last_name: string;
  mid_name: string | null;
  profile_photo_url: string | null;
  user_id: number;
}

/** Frontend camelCase Mapped Model: DeanProfile */
export interface DeanProfileModel {
  civilStatus: string;
  departmentId: number;
  firstName: string;
  gender: string;
  id: number;
  lastName: string;
  midName: string | null;
  profilePhotoUrl: string | null;
  userId: number;
}

/** Backend Model: Department (Table: `departments`) */
export interface BackendDepartment {
  building_id: number | null;
  cover_image_url: string | null;
  cover_original_url: string | null;
  deactivated_at: string | null;
  department_abbrev: string;
  department_name: string;
  description: string | null;
  id: number;
  is_active: boolean;
  logo_original_url: string | null;
  logo_url: string | null;
}

/** Frontend camelCase Mapped Model: Department */
export interface DepartmentModel {
  buildingId: number | null;
  coverImageUrl: string | null;
  coverOriginalUrl: string | null;
  deactivatedAt: string | null;
  departmentAbbrev: string;
  departmentName: string;
  description: string | null;
  id: number;
  isActive: boolean;
  logoOriginalUrl: string | null;
  logoUrl: string | null;
}

/** Backend Model: Enrollment (Table: `enrollments`) */
export interface BackendEnrollment {
  id: number;
  program_id: number;
  semester_number: number;
  set_id: number | null;
  student_profile_id: number;
  student_type: string | null;
  sy_id: number;
  year_level: number | null;
}

/** Frontend camelCase Mapped Model: Enrollment */
export interface EnrollmentModel {
  id: number;
  programId: number;
  semesterNumber: number;
  setId: number | null;
  studentProfileId: number;
  studentType: string | null;
  syId: number;
  yearLevel: number | null;
}

/** Backend Model: EnrollmentSetting (Table: `enrollment_settings`) */
export interface BackendEnrollmentSetting {
  id: number;
  updated_at: string | null;
}

/** Frontend camelCase Mapped Model: EnrollmentSetting */
export interface EnrollmentSettingModel {
  id: number;
  updatedAt: string | null;
}

/** Backend Model: EnrollmentSubject (Table: `enrollment_subjects`) */
export interface BackendEnrollmentSubject {
  id: number;
  subject_id: number;
}

/** Frontend camelCase Mapped Model: EnrollmentSubject */
export interface EnrollmentSubjectModel {
  id: number;
  subjectId: number;
}

/** Backend Model: GradingPeriodClosure (Table: `grading_period_closures`) */
export interface BackendGradingPeriodClosure {
  closed_at: string;
  closed_by: number | null;
  id: number;
  period: string;
  reason: string | null;
  semester_number: number;
}

/** Frontend camelCase Mapped Model: GradingPeriodClosure */
export interface GradingPeriodClosureModel {
  closedAt: string;
  closedBy: number | null;
  id: number;
  period: string;
  reason: string | null;
  semesterNumber: number;
}

/** Backend Model: InstructorAssignmentAuditLog (Table: `instructor_assignment_audit_logs`) */
export interface BackendInstructorAssignmentAuditLog {
  action: string;
  created_at: string;
  department_id: number | null;
  department_name: string | null;
  details: string | null;
  id: number;
  instructor_name: string | null;
  instructor_profile_id: number | null;
  ip_address: string | null;
  new_value: string | null;
  performed_by: number | null;
  performer_name: string | null;
  previous_value: string | null;
  role: string | null;
  school_year: string | null;
  semester_number: number | null;
  subject_code: string | null;
  subject_id: number | null;
  sy_id: number | null;
  teaching_term_id: number | null;
}

/** Frontend camelCase Mapped Model: InstructorAssignmentAuditLog */
export interface InstructorAssignmentAuditLogModel {
  action: string;
  createdAt: string;
  departmentId: number | null;
  departmentName: string | null;
  details: string | null;
  id: number;
  instructorName: string | null;
  instructorProfileId: number | null;
  ipAddress: string | null;
  newValue: string | null;
  performedBy: number | null;
  performerName: string | null;
  previousValue: string | null;
  role: string | null;
  schoolYear: string | null;
  semesterNumber: number | null;
  subjectCode: string | null;
  subjectId: number | null;
  syId: number | null;
  teachingTermId: number | null;
}

/** Backend Model: InstructorContactInfo (Table: `instructor_contact_info`) */
export interface BackendInstructorContactInfo {
  email: string;
  id: number;
  instructor_profile_id: number;
  mobile: string;
}

/** Frontend camelCase Mapped Model: InstructorContactInfo */
export interface InstructorContactInfoModel {
  email: string;
  id: number;
  instructorProfileId: number;
  mobile: string;
}

/** Backend Model: InstructorDailyHourCap (Table: `instructor_daily_hour_caps`) */
export interface BackendInstructorDailyHourCap {
  day_of_week: number;
  id: number;
  max_daily_hours: number;
}

/** Frontend camelCase Mapped Model: InstructorDailyHourCap */
export interface InstructorDailyHourCapModel {
  dayOfWeek: number;
  id: number;
  maxDailyHours: number;
}

/** Backend Model: InstructorDailyLoad (Table: `instructor_daily_loads`) */
export interface BackendInstructorDailyLoad {
  current_daily_hours: number;
  day_of_week: number;
  id: number;
  teaching_term_id: number;
}

/** Frontend camelCase Mapped Model: InstructorDailyLoad */
export interface InstructorDailyLoadModel {
  currentDailyHours: number;
  dayOfWeek: number;
  id: number;
  teachingTermId: number;
}

/** Backend Model: InstructorProfile (Table: `instructor_profiles`) */
export interface BackendInstructorProfile {
  civil_status: string;
  department_id: number;
  employee_id: string | null;
  first_name: string;
  gender: string;
  id: number;
  last_name: string;
  mid_name: string | null;
  profile_photo_url: string | null;
  user_id: number;
}

/** Frontend camelCase Mapped Model: InstructorProfile */
export interface InstructorProfileModel {
  civilStatus: string;
  departmentId: number;
  employeeId: string | null;
  firstName: string;
  gender: string;
  id: number;
  lastName: string;
  midName: string | null;
  profilePhotoUrl: string | null;
  userId: number;
}

/** Backend Model: InstructorScheduleProposalMeeting (Table: `instructor_schedule_proposal_meetings`) */
export interface BackendInstructorScheduleProposalMeeting {
  day_of_week: string;
  end_time: string;
  id: number;
  response_id: number;
  room_id: number;
  start_time: string;
}

/** Frontend camelCase Mapped Model: InstructorScheduleProposalMeeting */
export interface InstructorScheduleProposalMeetingModel {
  dayOfWeek: string;
  endTime: string;
  id: number;
  responseId: number;
  roomId: number;
  startTime: string;
}

/** Backend Model: InstructorScheduleResponse (Table: `instructor_schedule_responses`) */
export interface BackendInstructorScheduleResponse {
  created_at: string;
  dean_decision_note: string | null;
  dean_reviewed_at: string | null;
  dean_reviewed_by_user_id: number | null;
  id: number;
  instructor_id: number;
  reason: string | null;
  registrar_decision_note: string | null;
  registrar_reviewed_at: string | null;
  registrar_reviewed_by_user_id: number | null;
  regular_schedule_id: number;
  responded_at: string | null;
  response_type: string;
  status: string;
}

/** Frontend camelCase Mapped Model: InstructorScheduleResponse */
export interface InstructorScheduleResponseModel {
  createdAt: string;
  deanDecisionNote: string | null;
  deanReviewedAt: string | null;
  deanReviewedByUserId: number | null;
  id: number;
  instructorId: number;
  reason: string | null;
  registrarDecisionNote: string | null;
  registrarReviewedAt: string | null;
  registrarReviewedByUserId: number | null;
  regularScheduleId: number;
  respondedAt: string | null;
  responseType: string;
  status: string;
}

/** Backend Model: InstructorSubjectAssignment (Table: `instructor_subject_assignments`) */
export interface BackendInstructorSubjectAssignment {
  curriculum_detail_id: number;
  id: number;
  teaching_term_id: number;
}

/** Frontend camelCase Mapped Model: InstructorSubjectAssignment */
export interface InstructorSubjectAssignmentModel {
  curriculumDetailId: number;
  id: number;
  teachingTermId: number;
}

/** Backend Model: InstructorTeachingTerm (Table: `instructor_teaching_terms`) */
export interface BackendInstructorTeachingTerm {
  current_weekly_hours: number;
  dean_max_weekly_hours: number;
  id: number;
  instructor_profile_id: number;
  max_weekly_hours: number;
  registrar_max_weekly_hours: number;
  semester_number: number;
  sy_id: number;
}

/** Frontend camelCase Mapped Model: InstructorTeachingTerm */
export interface InstructorTeachingTermModel {
  currentWeeklyHours: number;
  deanMaxWeeklyHours: number;
  id: number;
  instructorProfileId: number;
  maxWeeklyHours: number;
  registrarMaxWeeklyHours: number;
  semesterNumber: number;
  syId: number;
}

/** Backend Model: IrregularSchedule (Table: `irregular_schedules`) */
export interface BackendIrregularSchedule {
  enrollment_id: number;
  id: number;
  regular_sched_id: number;
}

/** Frontend camelCase Mapped Model: IrregularSchedule */
export interface IrregularScheduleModel {
  enrollmentId: number;
  id: number;
  regularSchedId: number;
}

/** Backend Model: LabTimeSlot (Table: `lab_time_slots`) */
export interface BackendLabTimeSlot {
  end_time: string;
  id: number;
  is_active: boolean;
  start_time: string;
}

/** Frontend camelCase Mapped Model: LabTimeSlot */
export interface LabTimeSlotModel {
  endTime: string;
  id: number;
  isActive: boolean;
  startTime: string;
}

/** Backend Model: MajorScheduleAuditLog (Table: `major_schedule_audit_logs`) */
export interface BackendMajorScheduleAuditLog {
  action: string;
  day_of_week: string | null;
  department_abbrev: string | null;
  department_id: number;
  department_name: string | null;
  details: string | null;
  end_time: string | null;
  id: number;
  instructor_name: string | null;
  ip_address: string | null;
  meeting_kind: string | null;
  new_data: Record<string, unknown> | null;
  performer_name: string | null;
  previous_data: Record<string, unknown> | null;
  program_label: string | null;
  reason: string | null;
  role: string | null;
  room_name: string | null;
  schedule_id: number | null;
  school_year: string | null;
  semester_number: number | null;
  set_name: string | null;
  start_time: string | null;
  subject_label: string | null;
  submission_id: number | null;
  submission_version: number | null;
  sy_id: number | null;
  workspace: string;
}

/** Frontend camelCase Mapped Model: MajorScheduleAuditLog */
export interface MajorScheduleAuditLogModel {
  action: string;
  dayOfWeek: string | null;
  departmentAbbrev: string | null;
  departmentId: number;
  departmentName: string | null;
  details: string | null;
  endTime: string | null;
  id: number;
  instructorName: string | null;
  ipAddress: string | null;
  meetingKind: string | null;
  newData: Record<string, unknown> | null;
  performerName: string | null;
  previousData: Record<string, unknown> | null;
  programLabel: string | null;
  reason: string | null;
  role: string | null;
  roomName: string | null;
  scheduleId: number | null;
  schoolYear: string | null;
  semesterNumber: number | null;
  setName: string | null;
  startTime: string | null;
  subjectLabel: string | null;
  submissionId: number | null;
  submissionVersion: number | null;
  syId: number | null;
  workspace: string;
}

/** Backend Model: MajorScheduleDeletionNote (Table: `major_schedule_deletion_notes`) */
export interface BackendMajorScheduleDeletionNote {
  day_of_week: string | null;
  deleted_at: string;
  deleted_by_name: string | null;
  deleted_by_user_id: number | null;
  end_time: string | null;
  id: number;
  instructor_display: string | null;
  program_abbrev: string | null;
  reason: string;
  room_name: string | null;
  schedule_id: number;
  set_name: string | null;
  start_time: string | null;
  subject_code: string | null;
  subject_title: string | null;
  submission_id: number;
}

/** Frontend camelCase Mapped Model: MajorScheduleDeletionNote */
export interface MajorScheduleDeletionNoteModel {
  dayOfWeek: string | null;
  deletedAt: string;
  deletedByName: string | null;
  deletedByUserId: number | null;
  endTime: string | null;
  id: number;
  instructorDisplay: string | null;
  programAbbrev: string | null;
  reason: string;
  roomName: string | null;
  scheduleId: number;
  setName: string | null;
  startTime: string | null;
  subjectCode: string | null;
  subjectTitle: string | null;
  submissionId: number;
}

/** Backend Model: MajorScheduleEditRequest (Table: `major_schedule_edit_requests`) */
export interface BackendMajorScheduleEditRequest {
  decision_note: string | null;
  id: number;
  reason: string;
  requested_at: string;
  requested_by_user_id: number | null;
  reviewed_at: string | null;
  reviewed_by_user_id: number | null;
  status: string;
  submission_id: number;
}

/** Frontend camelCase Mapped Model: MajorScheduleEditRequest */
export interface MajorScheduleEditRequestModel {
  decisionNote: string | null;
  id: number;
  reason: string;
  requestedAt: string;
  requestedByUserId: number | null;
  reviewedAt: string | null;
  reviewedByUserId: number | null;
  status: string;
  submissionId: number;
}

/** Backend Model: MajorScheduleSubmission (Table: `major_schedule_submissions`) */
export interface BackendMajorScheduleSubmission {
  created_at: string;
  department_id: number;
  finalized_at: string | null;
  finalized_by_user_id: number | null;
  id: number;
  semester_number: number;
  status: string;
  submitted_at: string | null;
  submitted_by_user_id: number | null;
  sy_id: number;
  version: number;
}

/** Frontend camelCase Mapped Model: MajorScheduleSubmission */
export interface MajorScheduleSubmissionModel {
  createdAt: string;
  departmentId: number;
  finalizedAt: string | null;
  finalizedByUserId: number | null;
  id: number;
  semesterNumber: number;
  status: string;
  submittedAt: string | null;
  submittedByUserId: number | null;
  syId: number;
  version: number;
}

/** Backend Model: MajorScheduleSubmissionSet (Table: `major_schedule_submission_sets`) */
export interface BackendMajorScheduleSubmissionSet {
  id: number;
}

/** Frontend camelCase Mapped Model: MajorScheduleSubmissionSet */
export interface MajorScheduleSubmissionSetModel {
  id: number;
}

/** Backend Model: Notification (Table: `notifications`) */
export interface BackendNotification {
  id: number;
  is_read: boolean;
  payload: Record<string, unknown>;
  read_at: string | null;
  type: string;
}

/** Frontend camelCase Mapped Model: Notification */
export interface NotificationModel {
  id: number;
  isRead: boolean;
  payload: Record<string, unknown>;
  readAt: string | null;
  type: string;
}

/** Backend Model: Permission (Table: `permissions`) */
export interface BackendPermission {
  deactivated_at: string | null;
  description: string | null;
  id: number;
  is_active: boolean;
  permission_slug: string;
}

/** Frontend camelCase Mapped Model: Permission */
export interface PermissionModel {
  deactivatedAt: string | null;
  description: string | null;
  id: number;
  isActive: boolean;
  permissionSlug: string;
}

/** Backend Model: Prerequisite (Table: `prerequisites`) */
export interface BackendPrerequisite {
  id: number;
  prerequisite_id: number | null;
  subject_id: number | null;
}

/** Frontend camelCase Mapped Model: Prerequisite */
export interface PrerequisiteModel {
  id: number;
  prerequisiteId: number | null;
  subjectId: number | null;
}

/** Backend Model: Program (Table: `programs`) */
export interface BackendProgram {
  deactivated_at: string | null;
  department_id: number;
  id: number;
  is_active: boolean;
  program_abbrev: string;
  program_description: string | null;
  program_length: number;
  program_name: string;
  program_type: string;
}

/** Frontend camelCase Mapped Model: Program */
export interface ProgramModel {
  deactivatedAt: string | null;
  departmentId: number;
  id: number;
  isActive: boolean;
  programAbbrev: string;
  programDescription: string | null;
  programLength: number;
  programName: string;
  programType: string;
}

/** Backend Model: RegistrarContactInfo (Table: `registrar_contact_info`) */
export interface BackendRegistrarContactInfo {
  email: string;
  id: number;
  mobile: string;
  registrar_profile_id: number;
}

/** Frontend camelCase Mapped Model: RegistrarContactInfo */
export interface RegistrarContactInfoModel {
  email: string;
  id: number;
  mobile: string;
  registrarProfileId: number;
}

/** Backend Model: RegistrarMajorSchedule (Table: `registrar_major_schedules`) */
export interface BackendRegistrarMajorSchedule {
  id: number;
  mode: string;
  semester_number: number;
}

/** Frontend camelCase Mapped Model: RegistrarMajorSchedule */
export interface RegistrarMajorScheduleModel {
  id: number;
  mode: string;
  semesterNumber: number;
}

/** Backend Model: RegistrarProfile (Table: `registrar_profiles`) */
export interface BackendRegistrarProfile {
  civil_status: string;
  department_id: number;
  first_name: string;
  gender: string;
  id: number;
  last_name: string;
  mid_name: string | null;
  profile_photo_url: string | null;
  user_id: number;
}

/** Frontend camelCase Mapped Model: RegistrarProfile */
export interface RegistrarProfileModel {
  civilStatus: string;
  departmentId: number;
  firstName: string;
  gender: string;
  id: number;
  lastName: string;
  midName: string | null;
  profilePhotoUrl: string | null;
  userId: number;
}

/** Backend Model: RegularSchedule (Table: `regular_schedules`) */
export interface BackendRegularSchedule {
  created_by_user_id: number | null;
  day_id: number;
  department_id: number | null;
  id: number;
  instructor_id: number | null;
  is_draft: boolean;
  is_protected: boolean;
  major_workflow_status: string | null;
  mode: string;
  program_id: number;
  room_id: number;
  schedule_origin: string;
  semester_number: number;
  set_id: number;
  subject_id: number;
  sy_id: number;
}

/** Frontend camelCase Mapped Model: RegularSchedule */
export interface RegularScheduleModel {
  createdByUserId: number | null;
  dayId: number;
  departmentId: number | null;
  id: number;
  instructorId: number | null;
  isDraft: boolean;
  isProtected: boolean;
  majorWorkflowStatus: string | null;
  mode: string;
  programId: number;
  roomId: number;
  scheduleOrigin: string;
  semesterNumber: number;
  setId: number;
  subjectId: number;
  syId: number;
}

/** Backend Model: RevokedToken (Table: `revoked_tokens`) */
export interface BackendRevokedToken {
  id: number;
  jti: string;
}

/** Frontend camelCase Mapped Model: RevokedToken */
export interface RevokedTokenModel {
  id: number;
  jti: string;
}

/** Backend Model: Role (Table: `roles`) */
export interface BackendRole {
  id: number;
  role_name: string;
}

/** Frontend camelCase Mapped Model: Role */
export interface RoleModel {
  id: number;
  roleName: string;
}

/** Backend Model: RolePermission (Table: `role_permissions`) */
export interface BackendRolePermission {
  id: number;
  permission_id: number;
  role_id: number;
}

/** Frontend camelCase Mapped Model: RolePermission */
export interface RolePermissionModel {
  id: number;
  permissionId: number;
  roleId: number;
}

/** Backend Model: Room (Table: `rooms`) */
export interface BackendRoom {
  building_id: number;
  deactivated_at: string | null;
  floor_level: number;
  id: number;
  is_active: boolean;
  room_capacity: number;
  room_name: string;
  room_status: string;
  room_type: string;
  time_remaining: number | null;
}

/** Frontend camelCase Mapped Model: Room */
export interface RoomModel {
  buildingId: number;
  deactivatedAt: string | null;
  floorLevel: number;
  id: number;
  isActive: boolean;
  roomCapacity: number;
  roomName: string;
  roomStatus: string;
  roomType: string;
  timeRemaining: number | null;
}

/** Backend Model: ScheduleAuditLog (Table: `schedule_audit_logs`) */
export interface BackendScheduleAuditLog {
  action: string;
  details: string | null;
  id: number;
  ip_address: string | null;
  performer_name: string | null;
  program: string | null;
  role: string | null;
  school_year: string | null;
  semester_number: number | null;
  set_code: string | null;
}

/** Frontend camelCase Mapped Model: ScheduleAuditLog */
export interface ScheduleAuditLogModel {
  action: string;
  details: string | null;
  id: number;
  ipAddress: string | null;
  performerName: string | null;
  program: string | null;
  role: string | null;
  schoolYear: string | null;
  semesterNumber: number | null;
  setCode: string | null;
}

/** Backend Model: ScheduleStagingPlan (Table: `schedule_staging_plans`) */
export interface BackendScheduleStagingPlan {
  error: string | null;
  id: number;
  plan: Record<string, unknown> | null;
  program_id: number;
  semester_number: number;
  solved_at: string | null;
  stale: boolean;
  stats: Record<string, unknown> | null;
  status: string;
  sy_id: number;
}

/** Frontend camelCase Mapped Model: ScheduleStagingPlan */
export interface ScheduleStagingPlanModel {
  error: string | null;
  id: number;
  plan: Record<string, unknown> | null;
  programId: number;
  semesterNumber: number;
  solvedAt: string | null;
  stale: boolean;
  stats: Record<string, unknown> | null;
  status: string;
  syId: number;
}

/** Backend Model: SchedulingLoadPolicy (Table: `scheduling_load_policies`) */
export interface BackendSchedulingLoadPolicy {
  id: number;
  normal_load_hours: number;
  overload_daily_cap: number;
  regular_daily_cap: number;
  semester_number: number;
  sy_id: number;
  updated_at: string | null;
  updated_by: number | null;
}

/** Frontend camelCase Mapped Model: SchedulingLoadPolicy */
export interface SchedulingLoadPolicyModel {
  id: number;
  normalLoadHours: number;
  overloadDailyCap: number;
  regularDailyCap: number;
  semesterNumber: number;
  syId: number;
  updatedAt: string | null;
  updatedBy: number | null;
}

/** Backend Model: SchoolYear (Table: `school_years`) */
export interface BackendSchoolYear {
  completion_reason: string | null;
  id: number;
  registrar_completed_at: string | null;
  registrar_completed_by: number | null;
  school_year: string;
}

/** Frontend camelCase Mapped Model: SchoolYear */
export interface SchoolYearModel {
  completionReason: string | null;
  id: number;
  registrarCompletedAt: string | null;
  registrarCompletedBy: number | null;
  schoolYear: string;
}

/** Backend Model: Semester (Table: `semesters`) */
export interface BackendSemester {
  id: number;
  semester_name: string;
  semester_number: number;
}

/** Frontend camelCase Mapped Model: Semester */
export interface SemesterModel {
  id: number;
  semesterName: string;
  semesterNumber: number;
}

/** Backend Model: Set (Table: `sets`) */
export interface BackendSet {
  deactivated_at: string | null;
  id: number;
  is_active: boolean;
  program_id: number;
  set_code: string;
  year_level: number;
}

/** Frontend camelCase Mapped Model: Set */
export interface SetModel {
  deactivatedAt: string | null;
  id: number;
  isActive: boolean;
  programId: number;
  setCode: string;
  yearLevel: number;
}

/** Backend Model: SetScheduleRelease (Table: `set_schedule_releases`) */
export interface BackendSetScheduleRelease {
  approved_at: string | null;
  confirmed_daily_hour_increases: Record<string, unknown> | null;
  id: number;
  rejection_reason: string | null;
  reviewed_at: string | null;
  semester_number: number;
  submission_note: string | null;
  submitted_at: string | null;
}

/** Frontend camelCase Mapped Model: SetScheduleRelease */
export interface SetScheduleReleaseModel {
  approvedAt: string | null;
  confirmedDailyHourIncreases: Record<string, unknown> | null;
  id: number;
  rejectionReason: string | null;
  reviewedAt: string | null;
  semesterNumber: number;
  submissionNote: string | null;
  submittedAt: string | null;
}

/** Backend Model: StudentCreditedSubject (Table: `student_credited_subjects`) */
export interface BackendStudentCreditedSubject {
  id: number;
  subject_id: number;
}

/** Frontend camelCase Mapped Model: StudentCreditedSubject */
export interface StudentCreditedSubjectModel {
  id: number;
  subjectId: number;
}

/** Backend Model: StudentProfile (Table: `student_profiles`) */
export interface BackendStudentProfile {
  birthdate: string | null;
  deactivated_at: string | null;
  email: string;
  first_name: string;
  gender: string;
  id: number;
  is_active: boolean;
  last_name: string;
  mid_name: string | null;
  mobile: string;
  parent_contact: string | null;
  profile_photo_url: string | null;
  student_id: string | null;
  suffix: string | null;
  user_id: number | null;
}

/** Frontend camelCase Mapped Model: StudentProfile */
export interface StudentProfileModel {
  birthdate: string | null;
  deactivatedAt: string | null;
  email: string;
  firstName: string;
  gender: string;
  id: number;
  isActive: boolean;
  lastName: string;
  midName: string | null;
  mobile: string;
  parentContact: string | null;
  profilePhotoUrl: string | null;
  studentId: string | null;
  suffix: string | null;
  userId: number | null;
}

/** Backend Model: Subject (Table: `subjects`) */
export interface BackendSubject {
  created_at: string;
  deactivated_at: string | null;
  descriptive_title: string;
  id: number;
  is_active: boolean;
  subject_code: string;
  subject_type: string;
  units: number;
  updated_at: string;
}

/** Frontend camelCase Mapped Model: Subject */
export interface SubjectModel {
  createdAt: string;
  deactivatedAt: string | null;
  descriptiveTitle: string;
  id: number;
  isActive: boolean;
  subjectCode: string;
  subjectType: string;
  units: number;
  updatedAt: string;
}

/** Backend Model: SubjectHourOverride (Table: `subject_hour_overrides`) */
export interface BackendSubjectHourOverride {
  id: number;
  lab_hours: number;
  lecture_hours: number;
  meetings: number;
  note: string | null;
  semester_number: number;
  set_id: number | null;
  subject_id: number;
  sy_id: number;
}

/** Frontend camelCase Mapped Model: SubjectHourOverride */
export interface SubjectHourOverrideModel {
  id: number;
  labHours: number;
  lectureHours: number;
  meetings: number;
  note: string | null;
  semesterNumber: number;
  setId: number | null;
  subjectId: number;
  syId: number;
}

/** Backend Model: SubjectTimeAllocation (Table: `subject_time_allocations`) */
export interface BackendSubjectTimeAllocation {
  current_hours: number;
  days_count: number;
  id: number;
  semester_number: number;
  set_id: number;
  subject_id: number;
  sy_id: number;
}

/** Frontend camelCase Mapped Model: SubjectTimeAllocation */
export interface SubjectTimeAllocationModel {
  currentHours: number;
  daysCount: number;
  id: number;
  semesterNumber: number;
  setId: number;
  subjectId: number;
  syId: number;
}

/** Backend Model: SuperAdminContactInfo (Table: `super_admin_contact_info`) */
export interface BackendSuperAdminContactInfo {
  email: string;
  id: number;
  mobile: string;
  super_admin_profile_id: number;
}

/** Frontend camelCase Mapped Model: SuperAdminContactInfo */
export interface SuperAdminContactInfoModel {
  email: string;
  id: number;
  mobile: string;
  superAdminProfileId: number;
}

/** Backend Model: SuperAdminProfile (Table: `super_admin_profiles`) */
export interface BackendSuperAdminProfile {
  civil_status: string;
  department_id: number;
  first_name: string;
  gender: string;
  id: number;
  last_name: string;
  mid_name: string | null;
  profile_photo_url: string | null;
  user_id: number;
}

/** Frontend camelCase Mapped Model: SuperAdminProfile */
export interface SuperAdminProfileModel {
  civilStatus: string;
  departmentId: number;
  firstName: string;
  gender: string;
  id: number;
  lastName: string;
  midName: string | null;
  profilePhotoUrl: string | null;
  userId: number;
}

/** Backend Model: TeachingTermHoursAdjustmentRequest (Table: `teaching_term_hours_adjustment_requests`) */
export interface BackendTeachingTermHoursAdjustmentRequest {
  created_at: string;
  decided_at: string | null;
  decided_by_name: string | null;
  decided_by_role: string | null;
  decided_by_user_id: number | null;
  decision_message: string | null;
  id: number;
  previous_hours: number | null;
  reason: string;
  requested_by_name: string | null;
  requested_by_role: string | null;
  requested_by_user_id: number;
  requested_hours: number;
  status: string;
}

/** Frontend camelCase Mapped Model: TeachingTermHoursAdjustmentRequest */
export interface TeachingTermHoursAdjustmentRequestModel {
  createdAt: string;
  decidedAt: string | null;
  decidedByName: string | null;
  decidedByRole: string | null;
  decidedByUserId: number | null;
  decisionMessage: string | null;
  id: number;
  previousHours: number | null;
  reason: string;
  requestedByName: string | null;
  requestedByRole: string | null;
  requestedByUserId: number;
  requestedHours: number;
  status: string;
}

/** Backend Model: TermAuditLog (Table: `term_audit_logs`) */
export interface BackendTermAuditLog {
  action: string;
  details: string | null;
  id: number;
  ip_address: string | null;
  performer_name: string | null;
  role: string | null;
  school_year: string | null;
  semester_number: number | null;
}

/** Frontend camelCase Mapped Model: TermAuditLog */
export interface TermAuditLogModel {
  action: string;
  details: string | null;
  id: number;
  ipAddress: string | null;
  performerName: string | null;
  role: string | null;
  schoolYear: string | null;
  semesterNumber: number | null;
}

/** Backend Model: TermClosure (Table: `term_closures`) */
export interface BackendTermClosure {
  closed_at: string;
  closed_by: number | null;
  id: number;
  reason: string | null;
  semester_number: number;
  sy_id: number;
}

/** Frontend camelCase Mapped Model: TermClosure */
export interface TermClosureModel {
  closedAt: string;
  closedBy: number | null;
  id: number;
  reason: string | null;
  semesterNumber: number;
  syId: number;
}

/** Backend Model: TextPrerequisite (Table: `text_prerequisites`) */
export interface BackendTextPrerequisite {
  id: number;
  prerequisite_text: string;
  subject_id: number;
}

/** Frontend camelCase Mapped Model: TextPrerequisite */
export interface TextPrerequisiteModel {
  id: number;
  prerequisiteText: string;
  subjectId: number;
}

/** Backend Model: User (Table: `users`) */
export interface BackendUser {
  deactivated_at: string | null;
  email: string;
  id: number;
  is_active: boolean;
  is_temp: number;
  password_hash: string;
}

/** Frontend camelCase Mapped Model: User */
export interface UserModel {
  deactivatedAt: string | null;
  email: string;
  id: number;
  isActive: boolean;
  isTemp: number;
  passwordHash: string;
}

/** Backend Model: UserRole (Table: `user_roles`) */
export interface BackendUserRole {
  id: number;
  role_id: number;
  user_id: number;
}

/** Frontend camelCase Mapped Model: UserRole */
export interface UserRoleModel {
  id: number;
  roleId: number;
  userId: number;
}

/** Backend Model: WeeklyHourAllocation (Table: `weekly_hour_allocations`) */
export interface BackendWeeklyHourAllocation {
  id: number;
  lab_hours: number;
  lecture_hours: number;
  meetings: number;
  subject_type: string;
}

/** Frontend camelCase Mapped Model: WeeklyHourAllocation */
export interface WeeklyHourAllocationModel {
  id: number;
  labHours: number;
  lectureHours: number;
  meetings: number;
  subjectType: string;
}

/** Backend Model: WeeklyHourAllocationPattern (Table: `weekly_hour_allocation_patterns`) */
export interface BackendWeeklyHourAllocationPattern {
  duration_hours: number;
  id: number;
  meetings: number;
  priority: number;
}

/** Frontend camelCase Mapped Model: WeeklyHourAllocationPattern */
export interface WeeklyHourAllocationPatternModel {
  durationHours: number;
  id: number;
  meetings: number;
  priority: number;
}
